customCommands:
  - key: "E"
    command: 'nvim -- {{.SelectedLocalFile.Name | quote}} +"DiffviewOpen HEAD -- %" +tabonly'
    context: "files"
    description: "Open selected file vs HEAD in Diffview.nvim"
    output: terminal
  - key: "<c-g>"
    command: "nvim +DiffviewOpen +tabonly"
    context: "files"
    description: "Open Diffview.nvim"
    output: terminal
